### ISSUE TITLE
compilation error with gpu

### ISSUE THREAD

**Issue by shabnam8920** [khavernathy/mcmd#74]
I received the following error when compiling with gpu:

bonding.cpp(146): warning: variable "smallest_bi" was set but never used

md_functions.cpp(30): warning: variable "dt" was declared but never referenced

md.cpp(14): warning: variable "n" was declared but never referenced

io.cpp(880): warning: variable "lx" was declared but never referenced

io.cpp(1848): warning: variable "DEBYE2SKA" was declared but never referenced

averages.cpp(642): warning: variable "dt" was declared but never referenced

main.cpp(457): warning: variable "total_steps" was declared but never referenced

cudafuncs.cu(7): error: function "atomicAdd(double *, double)" has already been defined

1 error detected in the compilation of "/tmp/tmpxft_00008d90_00000000-4_main.cpp4.ii".

#

**Comment by khavernathy** [comment]
Looks like atomicAdd doesn't need to be manually defined in newer CUDA architectures 

You could try to pull the repo again via `git pull` and recompile

Changed via 2ea84ed1782acdc8b7236e9e1c75949d2b06ac7a

**Comment by khavernathy** [comment]
What GPU are you using? This issue should depend on the compute capability (https://en.m.wikipedia.org/wiki/CUDA#Version_features_and_specifications).
Compute capability 1.3 or higher supports double-floating point operations but older ones do not, so there is a custom definition of atomicAdd in cudafuncs.cu.

You could probably delete the function atomicAdd  at the beginning of cudafuncs.cu and then recompile.
