### ISSUE TITLE
Error while running "bash compile.sh" in cygwin

### ISSUE THREAD

**Issue by mitkumarpaul** [khavernathy/mcmd#77]
getting this error

Doing serial GCC (1 processor) compilation for CPU
In file included from main.cpp:49:0:
usefulmath.cpp: In function 'double erfInverse(double)':
usefulmath.cpp:34:14: error: 'M_PI' was not declared in this scope
     tt1 = 2/(M_PI*0.147) + 0.5 * lnx;
              ^~~~
In file included from main.cpp:50:0:
classes.cpp: In member function 'void Pbc::calcCarBasis()':
classes.cpp:554:23: error: 'M_PI' was not declared in this scope
         alpha = 180.0/M_PI*acos( dddotprod(basis[1],basis[2]) / sqrt( dddotprod(basis[1], basis[1]) * dddotprod(basis[2], basis[2]) ));
                       ^~~~
classes.cpp: In member function 'void Pbc::calcNormalBasis()':
classes.cpp:567:23: error: 'M_PI' was not declared in this scope
         b0[1] = b*cos(M_PI/180.0 * gamma);
                       ^~~~
In file included from main.cpp:50:0:
classes.cpp: In member function 'void Molecule::printAll()':
classes.cpp:1078:33: error: 'M_PI' was not declared in this scope
                ang_pos[0]*180.0/M_PI, ang_pos[1]*180.0/M_PI, ang_pos[2]*180.0/M_PI); //com[0], com[1], com[2]);
                                 ^~~~
In file included from main.cpp:52:0:
fugacity.cpp: In function 'double h2_comp_back(double, double)':
fugacity.cpp:123:10: error: 'M_PI' was not declared in this scope
     y = (M_PI*sqrt(2.0)/6.0)*(pressure*ATM2PASCALS*1.0e-6)/(NA_MPMC*KB_MPMC*temperature)*V0;
          ^~~~
In file included from main.cpp:52:0:
fugacity.cpp: In function 'double ch4_comp_back(double, double)':
fugacity.cpp:312:10: error: 'M_PI' was not declared in this scope
     y = (M_PI*sqrt(2.0)/6.0)*(pressure*ATM2PASCALS*1.0e-6)/(NA_MPMC*KB_MPMC*temperature)*V0;
          ^~~~
fugacity.cpp: In function 'double n2_comp_back(double, double)':
fugacity.cpp:570:10: error: 'M_PI' was not declared in this scope
     y = (M_PI*sqrt(2.0)/6.0)*(pressure*ATM2PASCALS*1.0e-6)/(NA_MPMC*KB_MPMC*temperature)*V0;
          ^~~~
In file included from main.cpp:54:0:
system_functions.cpp: In function 'double getrand()':
system_functions.cpp:24:20: error: 'drand48' was not declared in this scope
     return drand48();
                    ^
In file included from main.cpp:55:0:
bonding.cpp: In function 'void setBondingParameters(System&)':
bonding.cpp:1449:59: error: 'M_PI' was not declared in this scope
             system.constants.uniqueAngles[it].theta_ijk = M_PI/180.0*system.constants.UFF_angles[system.molecules[mol].atoms[atom2].UFFlabel.c_str()];
                                                           ^~~~
bonding.cpp:1479:70: error: 'M_PI' was not declared in this scope
             if (fabs(system.constants.uniqueDihedrals[it].value*180./M_PI - 60.) < 10)
                                                                      ^~~~
bonding.cpp:1488:71: error: 'M_PI' was not declared in this scope
             system.constants.uniqueDihedrals[it].phi_ijkl = params[0]*M_PI/180.0;
                                                                       ^~~~
bonding.cpp:1490:71: error: 'M_PI' was not declared in this scope
             system.constants.uniqueDihedrals[it].phi_ijkl = params[0]*M_PI/180.0;
                                                                       ^~~~
In file included from potential.cpp:11:0,
                 from mc.cpp:9,
                 from main.cpp:56:
lj.cpp: In function 'double self_lj_lrc(System&)':
lj.cpp:74:52: error: 'M_PI' was not declared in this scope
                         this_self_lrc = (16.0/3.0)*M_PI*eps*sig3*((1.0/3.0)*sigcut9 - sigcut3)/volume;
                                                    ^~~~
lj.cpp: In function 'double lj(System&)':
lj.cpp:167:65: error: 'M_PI' was not declared in this scope
                                 double this_rd_lrc = (16.0/3.0)*M_PI*eps*sig3*((1.0/3.0)*sigcut9 - sigcut3)/volume;
                                                                 ^~~~
In file included from potential.cpp:13:0,
                 from mc.cpp:9,
                 from main.cpp:56:
coulombic.cpp: In function 'double coulombic_self(System&)':
coulombic.cpp:61:32: error: 'M_PI' was not declared in this scope
     const double sqrtPI = sqrt(M_PI);
                                ^~~~
coulombic.cpp: In function 'void coulombic_real_force(System&)':
coulombic.cpp:359:32: error: 'M_PI' was not declared in this scope
     const double sqrtPI = sqrt(M_PI);
                                ^~~~
coulombic.cpp: In function 'double coulombic_reciprocal(System&)':
coulombic.cpp:499:37: error: 'M_PI' was not declared in this scope
                         k[p] += 2.0*M_PI*system.pbc.reciprocal_basis[p][q] * l[q];
                                     ^~~~
coulombic.cpp:527:24: error: 'M_PI' was not declared in this scope
     potential *= 4.0 * M_PI / system.pbc.volume; // note, this is double the conventional potential because we only summed a half-ewald-sphere
                        ^~~~
In file included from potential.cpp:15:0,
                 from mc.cpp:9,
                 from main.cpp:56:
tt.cpp: In function 'double tt_lrc(System&, double, double, double)':
tt.cpp:20:17: error: 'M_PI' was not declared in this scope
     return -4.0*M_PI*(c6/(3.0*rc*rc2) + c8/(5.0*rc5) + c10/(7.0*rc5*rc2))/system.pbc.volume;
                 ^~~~
tt.cpp: In function 'double tt_self(System&, int, int)':
tt.cpp:31:17: error: 'M_PI' was not declared in this scope
     return -4.0*M_PI*(c6/(3.0*rc2*rc) + c8/(5.0*rc5) + c10/(7.0*rc5*rc2))/system.pbc.volume;
                 ^~~~
In file included from mc.cpp:10:0,
                 from main.cpp:56:
rotatepoint.cpp: In function 'double* rotatePoint(System&, double, double, double, int, double)':
rotatepoint.cpp:14:19: error: 'M_PI' was not declared in this scope
     angle = angle*M_PI/180.0;
                   ^~~~
In file included from main.cpp:63:0:
io.cpp: In function 'void writeLAMMPSfiles(System&)':
io.cpp:888:35: error: 'M_PI' was not declared in this scope
     double alpha=system.pbc.alpha*M_PI/180.;
                                   ^~~~
In file included from main.cpp:64:0:
optimize.cpp: In function 'void printBondParameters(System&)':
optimize.cpp:79:77: error: 'M_PI' was not declared in this scope
         double theta_ijk = system.constants.uniqueAngles[n].theta_ijk*180.0/M_PI;
                                                                             ^~~~
optimize.cpp:105:78: error: 'M_PI' was not declared in this scope
         double phi_ijkl = system.constants.uniqueDihedrals[n].phi_ijkl*180.0/M_PI;
                                                                              ^~~~
optimize.cpp:139:27: error: 'M_PI' was not declared in this scope
                value*180./M_PI);
                           ^~~~
In file included from main.cpp:65:0:
radial_dist.cpp: In function 'double sphere_volume(double)':
radial_dist.cpp:21:22: error: 'M_PI' was not declared in this scope
     return (4.0/3.0)*M_PI*(r*r*r);
                      ^~~~
main.cpp: In function 'int main(int, char**)':
main.cpp:135:33: error: 'srand48' was not declared in this scope
     srand48((unsigned)time(NULL)); // initiate drand48 48-bit integer random seed.
                                 ^

**Comment by khavernathy** [comment]
Better to use `bash compile.sh windows`.

And you might need to uncomment these 3 lines in `src/main.cpp` and try to compile again.

Windows environments don't have `M_PI` pre-defined.

https://github.com/khavernathy/mcmd/blob/dc0ebfeb1e97a0a0c434c4eea803bd5f8c5776e7/src/main.cpp#L37


Or simply add
```
#ifndef M_PI
    #define M_PI 3.14159265358979323846
#endif
```

at/near the top of `src/main.cpp`.

**Comment by khavernathy** [comment]
I  committed this change to the main branch. These errors shouldn't appear anymore if you pull the latest changes and re-compile. Closing issue.
